### ISSUE TITLE
Return Type mismatch

### ISSUE THREAD

**Issue by EnderGnar** [minirust/minirust#116]
It is currently possible to call functions with mismatching return types. It is possible to return a `u64` from a function and give a `u8` as the place to put it in.

Here is a code snippet that shows this behavior. I have it on [this branch](https://github.com/EnderGnar/minirust/tree/ret-mismatch).
```rust
use crate::*;

#[test]
fn ret_mismatch() {
    // function that returns a u64
    let other_f = {
        let locals = [<u64>::get_ptype()];
        let b0 = block!(
            assign(local(0), const_int::<u64>(0)),
            return_()
        );

        function(Ret::Yes, 0, &locals, &[b0])
    };

    let locals = [<u8>::get_ptype()];

    let b0 = block!(
        storage_live(0),
        // call to the function with a u8 place to put the value into.
        call(1, &[], Some(local(0)), Some(1))
    );
    let b1 = block!(exit());

    let f = function(Ret::No, 0, &locals, &[b0, b1]);
    let p = program(&[f, other_f]);
    dump_program(p);
    assert_stop(p);
}
```

Not shown in this example is that it is also possible with values that don't fit into a `u8`.

**Comment by RalfJung** [comment]
The matching return types are supposed to be checked by the `ArgAbi`. I guess the MiniRust builder here implicitly sets the `Register` which then allows mismatching sizes.

**Comment by mattheww** [comment]
> What confuses me is why this doesn't cause an out-of-bounds access when it stores the u64 into the u8 place.

I think that's because `eval_terminator` for `Return` uses the caller's idea of the return type for the copy.

If I swap the `u8` and `u64` in that example, I do get the runtime error (either 'insufficiently aligned' or 'out-of-bounds').

**Comment by RalfJung** [comment]
@EnderGnar and me discussed this and we will re-instante the size check on function calls to avoid this surprising asymmetry.
