### ISSUE TITLE
Minimize: restructure `ConstValue` minimization

### ISSUE THREAD

**Issue by essickmango** [minirust/minirust#158]
Currently the minimizer only supports a few const values, and it assumes they are all represented as scalars.
However what should actually happen is that it should recursively translate the const value using the API from https://github.com/rust-lang/rust/pull/121396, and therefore support arbitrary types.

**Comment by RalfJung** [comment]
So to make this a bit more concrete, this is about `translate_const_val`. That should start by calling `let (ecx, val) = mk_eval_cx_for_const_val`, and then match on the type (which it already does) and then use methods like `ecx.read_scalar` and `ecx.project_field` to recurse over the `val`.

Also, we should not be calling `eval_to_allocation_raw`. That has `raw` in its name for a reason. Quoting from its doc comment:
> **Do not use this** directly, use the `eval_to_const_value` or `eval_to_valtree` instead.

**Comment by RalfJung** [comment]
Fixed by https://github.com/minirust/minirust/pull/182
