### ISSUE TITLE
raw_eq intrinsic is not supported

### ISSUE THREAD

**Issue by RalfJung** [minirust/minirust#176]
This occurs for instance [here](https://github.com/minirust/minirust/blob/c91adf155212f6197631cb560247ec604b1f003d/tooling/minimize/tests/pass/union.rs#L73), via the PartialEq impl for arrays of integers.

**Comment by bifbof** [comment]
Here is a minimal testcase for this issue: 

```rust
fn main() {
    let _ = [0] == [0];
}
```

outputs:
```
thread 'rustc' panicked at minimize/src/bb.rs:205:25:
unsupported Rust intrinsic `raw_eq`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
