### ISSUE TITLE
Add missing operators

### ISSUE THREAD

**Issue by RalfJung** [minirust/minirust#186]
Rust has a bunch of operators that we do not support yet:
- [x] BitOr, BitXor (on integers and Booleans)
- [x] Shl, Shr
- [x] Cmp
- [x] checked operators (in MIR encoded via a separate `Rvalue::CheckedBinaryOp`) -- AFAIK this is only allowed for Add, Sub, Mul; they should become separate BinOp for us
- [x] some intrinsics that are lowered to binops: AddUnchecked, SubUnchecked, MulUnchecked, ShlUnchecked, ShrUnchecked
- [x] `UnOp::Not`, which we support for Booleans but not for integers
- [x] Comparison operators on `bool` (here it seems best to not add anything new to MiniRust, and teach minimize to translate this to operations on integers)
- [x] Comparison operators on pointers (probably also best done via casts)

**Comment by bifbof** [comment]
The boolean comparison operators are also not supported yet:
```rust
fn main() {
    let _ = false < true;
    let _ = false <= true;
    let _ = false == true;
    let _ = false >= true;
    let _ = false > true;
}
```

**Comment by RalfJung** [comment]
We could handle those in minimize, by just casting to int and comparing there.

**Comment by bifbof** [comment]
On a similar note the comparison for pointers is also not supported:
```rust
fn main() {
    let a = &42 as *const i32;
    let b = &21 as *const i32;
    let _ = a == b;
}
```

**Comment by RalfJung** [comment]
That too should IMO be done via casts to integers; we'll have to add new casts for that.

**Comment by RalfJung** [comment]
> That too should IMO be done via casts to integers; we'll have to add new casts for that.

In fact we do not, we can just transmute to integers. Under our current provenance model, that has exactly the right behavior.
