### ISSUE TITLE
minimize: Add support for `NullaryOp`

### ISSUE THREAD

**Issue by bifbof** [minirust/minirust#201]
Currently we cannot translate the following code:
```rust
fn main() {
    ub_checks!(false);
    let _ = std::mem::size_of::<u32>();
    let _ = std::mem::align_of::<u32>();
    let _ = std::mem::offset_of!(F, field);
}
```
This is due to `NullaryOp` not being fully translated in all cases:

```
error: internal compiler error: minimize/src/rvalue.rs:234:18: rvalue failed to translate: NullaryOp(OffsetOf([(VariantIdx(0), 0)]), Ty { id: 2, kind: RigidTy(Adt(AdtDef(DefId { id: 0, name: "F" }), GenericArgs([]))) })
 --> tooling/minimize/fails/temptempfile.rs:8:13
  |
8 |     let _ = std::mem::offset_of!(F, field);
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error: internal compiler error originates in the macro `std::mem::offset_of` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at minimize/src/rvalue.rs:234:18:
Box<dyn Any>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: aborting due to 1 previous error
```

**Comment by RalfJung** [comment]
These should probably become intrinsics in MiniRust.

**Comment by RalfJung** [comment]
Thinking about it again, we should make things operators whenever they are read-only and deterministic. So adding `NullaryOp` sounds good to me.

**Comment by RalfJung** [comment]
Though `offset_of!` I am fairly sure I want to make a constant... so maybe they should just all be constants?

**Comment by sun-jacobi** [comment]
If we want to calculate the `offset_of` in the `minimize`, we might need to bump the rust version to use this method: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.offset_of_subfield
